# Copyright (c) Vaimo Group. All rights reserved.
# See LICENSE_VAIMO.txt for license details.
language: php
php:
  - '5.3.9' 
  - '5.4.45' 
  - '5.5.38' 
  - '5.6.40' 
  - '7.0.33' 
  - '7.1.32' 
  - '7.2.22' 
  - '7.3.25'
  - '7.4.13'
  - '8.0.0'
  
git:
  depth: 1

cache:
  directories:
    - "$HOME/.cache/composer"
    - "$HOME/.composer/cache"

install:
  - composer self-update 1.8.4
  - composer install

script:
  - "composer code:analyse"
  - "composer code:deps current"
