# Copyright (c) Vaimo Group. All rights reserved.
# See LICENSE_VAIMO.txt for license details.
language: php
  
git:
  depth: 1

cache:
  directories:
    - "$HOME/.cache/composer"
    - "$HOME/.composer/cache"

env:
  jobs:
    - COMPOSER_VERSION=1.8.4
    - COMPOSER_VERSION=2.0.9

script:
  - composer self-update ${COMPOSER_VERSION}
  - cp test/files/composer-v${COMPOSER_VERSION:0:1}.json composer.json 2>/dev/null || true
  - cp test/files/composer-v${COMPOSER_VERSION:0:1}.lock composer.lock 2>/dev/null || true
  - composer install
  - composer ci:build