# Copyright (c) Vaimo Group. All rights reserved.
# See LICENSE_VAIMO.txt for license details.
language: php
  
git:
  depth: 1

cache:
  directories:
    - "$HOME/.cache/composer"
    - "$HOME/.composer/cache"

install:
  - composer self-update 1.8.4
  - composer install

script:
  - "composer code:analyse"
  - "composer code:deps current"
